name: Linux, gcc

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [ia32, x64, aa64, arm, riscv64, mips64]
        include:
          - arch: ia32
            dir: ia32
            gcc: multilib
            cross_compile:
          - arch: x64
            dir: x86_64
            gcc: multilib
            cross_compile:
          - arch: aa64
            dir: aarch64
            gcc: aarch64-linux-gnu
            cross_compile: aarch64-linux-gnu-
          - arch: arm
            dir: arm
            gcc: arm-linux-gnueabihf
            cross_compile: arm-linux-gnueabihf-
          - arch: riscv64
            dir: riscv64
            gcc: riscv64-linux-gnu
            cross_compile: riscv64-linux-gnu-
          - arch: mips64
            dir: mips64el
            gcc: mips64el-linux-gnuabi64
            cross_compile: mips64el-linux-gnuabi64-
#          - arch: loongarch64
#            dir: loongarch64
#            gcc: loongarch64-linux-gnu
#            cross_compile: loongarch64-linux-gnu-

    steps:
    - name: Install toolchain
      run: |
        sudo apt-get update
        sudo apt-get install gcc-${{ matrix.gcc }}

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build
      run: make ARCH=${{ matrix.arch }} CROSS_COMPILE=${{ matrix.cross_compile }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.arch }}
        path: ./${{ matrix.dir }}/apps/*.efi