name: Linux, MinGW

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch: [x64, ia32]
        include:
        - arch: x64
          dir: x86_64
          pkg: gcc-mingw-w64-x86-64
          tuple: x86_64-w64-mingw32-
        - arch: ia32
          dir: ia32
          pkg: gcc-mingw-w64-i686
          tuple: i686-w64-mingw32-

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install gcc toolchain
      run: sudo apt install ${{ matrix.pkg }}

    - name: Build
      run: make ARCH=${{ matrix.arch }} CROSS_COMPILE=${{ matrix.tuple }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.arch }}
        path: ./${{ matrix.dir }}/apps/*.efi
