name: Windows, VS2022

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64, ia32, aa64, arm]
        conf: [Debug, Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Build
      shell: cmd
      run: msbuild ./gnu-efi.sln /m /p:Configuration=${{ matrix.conf }},Platform=${{ matrix.arch }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: ${{ matrix.conf == 'Release' }}
      with:
        name: ${{ matrix.arch }}
        path: ./${{ matrix.arch }}/${{ matrix.conf }}/*.efi
