name: Windows, MinGW

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64, ia32]
        include:
          - arch: x64
            dir: x86_64 
            sys: mingw64
            env: x86_64
          - arch: ia32
            dir: ia32
            sys: mingw32
            env: i686

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Install MinGW
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: >-
          mingw-w64-${{ matrix.env }}-toolchain
          base-devel
          git

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build
      run: make

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.arch }}
        path: ./${{ matrix.dir }}/apps/*.efi
